### ISSUE TITLE
TypeError: Assignment to constant variable.

### ISSUE THREAD

**Issue by TobiasHennig** [chuckdumont/webpack-hasjs-plugin#2]
If i turn on the "coerceUndefinedToFalse" option and a variable is undefined, the console throws the following error: `TypeError: Assignment to constant variable.`.

The problem is that you define a constant in line 2, which you overwrite in line 36. If you use **let** instead of **const** everything is fine.

Perhaps you want to try [eslint](https://eslint.org/docs/user-guide/getting-started) to prevent these kind of errors.

Thank you very much for this plugin, it makes a migration from requirejs so much easier. 🙏

**Comment by chuckdumont** [comment]
Ouch.  Thanks for reporting this.  It's fixed in v1.0.3.

I'm familiar with eslint and I use it in other projects.  I didn't use it here because I considered this project to be too small to need it (lol).  I'll add it if there are any substantial changes in the future.
